### PR TITLE
dynamodb: add support for streams API

### PR DESCRIPTION
**Pull request by aalness**

### CODE REVIEW

**Comment by aalness** [comment]
Also, I'm not sure if you guys are aware of this or not but to test my code against the local DynamoDB server I had to apply this patch:

```diff
diff --git a/dynamodb/dynamodb_test.go b/dynamodb/dynamodb_test.go
index 729a8a1..98c37a7 100755
--- a/dynamodb/dynamodb_test.go
+++ b/dynamodb/dynamodb_test.go
@@ -131,7 +131,7 @@ func (s *DynamoDBTest) WaitUntilStatus(c *C, status string) {
 }
 
 func setUpAuth(c *C) {
-       if !*amazon {
+       if *amazon {
                c.Skip("Test against amazon not enabled.")
        }
        if *local {
```

Note though that when I did I noticed `item_test.go` had 2 panics in it (pre-my change). I didn't make this change in case it was intentional for some reason.

**Comment by aalness** [comment]
I should add I've performed a significant amount of testing in AWS with a real table and things seem good there as well.

**Comment by boyand** [comment]
hey @aalness, it looks good to me as well. Great work

**Comment by aalness** [comment]
Thanks! I hope it's useful to others.

**Pull request merged**
